# Generated by Django 2.0 on 2019-11-29 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('p_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='病人编号')),
                ('p_name', models.CharField(max_length=20, verbose_name='病人姓名')),
                ('p_sex', models.CharField(choices=[('female', '女'), ('male', '男')], max_length=10, verbose_name='性别')),
                ('amount', models.IntegerField(default=0, verbose_name='图像数量')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='医生工号')),
                ('user_name', models.CharField(max_length=20, verbose_name='医生姓名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
            ],
            options={
                'verbose_name': '医生账户信息',
                'verbose_name_plural': '医生账户信息',
            },
        ),
        migrations.CreateModel(
            name='USimage',
            fields=[
                ('us_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='图片编号')),
                ('result', models.CharField(choices=[('-1', '未知'), ('0', '正常'), ('1', '患病')], max_length=5, verbose_name='筛查结果')),
                ('image', models.ImageField(upload_to='img')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Patient', verbose_name='病人编号')),
            ],
        ),
    ]
